name: Build CI

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  linux_job:
    name: Building for Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Setup premake
      uses: abel0b/setup-premake@v2.1
      with:
        version: "5.0.0-beta1"
    - name: Generating makefiles
      run: premake5 gmake2
    - name: Installing GTK3
      run: sudo apt-get install libgtk-3-dev
    - name: Building..
      run: make config=release_linux
    - uses: actions/upload-artifact@v3
      with:
        name: EMVParserToolLinux
        path: bin/Linux/Release/EmvParser
        retention-days: 2
    - uses: edgarrc/action-7z@v1
      with:
        args: 7z a -t7z -mx=9 bin/Linux/Release/EmvParserLinux.7z bin/Linux/Release/EmvParser
    - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%d-%m-%Y')"
    - name: Generate Release Notes
      uses: johnyherangi/create-release-notes@main
      id: generate_changelog
      with:
        format: '- {{subject}}'
      env:
          GITHUB_TOKEN: ${{ github.token }}
    - name: Create Release
      uses: actions/create-release@v1
      id: create_release
      with:
            draft: false
            prerelease: false
            release_name: v${{ steps.date.outputs.date }}
            tag_name: v${{ steps.date.outputs.date }}
            body: ${{steps.generate_changelog.outputs.release-notes}}
      env:
          GITHUB_TOKEN: ${{ github.token }}
    - name: Upload Package
      uses: actions/upload-release-asset@v1
      with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: bin/Linux/Release/EmvParserLinux.7z
            asset_name: EmvParserLinux.7z
            asset_content_type: application/x-7z-compressed
      env:
          GITHUB_TOKEN: ${{ github.token }}
  windows_job:
    name: Builiding for Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
            submodules: 'recursive'
      - name: Install premake5
        run: choco install premake5 --pre
      - name: Generating Visual Studio Solution
        run: premake5 vs2019
      - name: Add msbuild (x86) to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Build app for release 32bits
        run: msbuild EmvParser.sln -t:rebuild -verbosity:diag -property:Configuration=Release -property:Platform=Win32
      - name: Add msbuild (x64) to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
      - name: Build app for release 64bits
        run: msbuild EmvParser.sln -t:rebuild -verbosity:diag -property:Configuration=Release -property:Platform=Win64
      - uses: actions/upload-artifact@v3
        with:
            name: EMVParserTool32
            path: bin/Win32/Release/EmvParser.exe
            retention-days: 2
      - uses: actions/upload-artifact@v3
        with:
            name: EMVParserTool64
            path: bin/Win64/Release/EmvParser.exe
            retention-days: 2
      - uses: edgarrc/action-7z@v1
        with:
          args: 7z a -t7z -mx=9 bin/Linux/Release/EMVParserTool32.7z bin/Win32/Release/EmvParser.exe
      - uses: edgarrc/action-7z@v1
        with:
          args: 7z a -t7z -mx=9 bin/Linux/Release/EMVParserTool64.7z bin/Win64/Release/EmvParser.exe
      - name: Upload Package
        uses: actions/upload-release-asset@v1
        with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: bin/Linux/Release/EMVParserTool32.7z
            asset_name: EMVParserTool32.7z
            asset_content_type: application/x-7z-compressed
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload Package
        uses: actions/upload-release-asset@v1
        with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: bin/Linux/Release/EMVParserTool64.7z
            asset_name: EMVParserTool64.7z
            asset_content_type: application/x-7z-compressed
        env:
          GITHUB_TOKEN: ${{ github.token }}
